/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_ffmpegtest_FFmpegTools */

#ifndef _Included_com_thinking_ffmpegtest_FFmpegTools
#define _Included_com_thinking_ffmpegtest_FFmpegTools
#ifdef __cplusplus
extern "C" {
#endif
	//由于ffmpeg是纯C写的，所以所有的include必须包含在extern "C"内
#include<libavcodec\avcodec.h>
	/*
	 * Class:     com_thinking_ffmpegtest_FFmpegTools
	 * Method:    test
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_ffmpegtest_FFmpegTools_test
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
