/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<android\log.h>
/* Header for class com_thinking_ffmpegtest_FFmpegTools */

#ifndef INT64_C
#define INT64_C
#define UINT64_C
#endif

#ifndef _Included_com_thinking_ffmpegtest_FFmpegTools
#define _Included_com_thinking_ffmpegtest_FFmpegTools

#ifdef __cplusplus
extern "C" {
#endif

	//由于ffmpeg是纯C写的，所以所有的include必须包含在extern "C"内
#include<libavcodec\avcodec.h>
#include<libavformat\avformat.h>
#include<libavutil\time.h>
#include<libavutil\imgutils.h>
	/*
	 * Class:     com_thinking_cameralive_new_func_FFmpeg
	 * Method:    ffmpegInit
	 * Signature: (IILjava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_thinking_cameralive_new_1func_FFmpeg_ffmpegInit
		(JNIEnv *, jclass, jint, jint, jstring);

	/*
	 * Class:     com_thinking_cameralive_new_func_FFmpeg
	 * Method:    ffmpegPush
	 * Signature: ([B)I
	 */
	JNIEXPORT jint JNICALL Java_com_thinking_cameralive_new_1func_FFmpeg_ffmpegPush
		(JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
